version: "3.8"

services:
  app:
    container_name: python-lab1
    build:
      context: .
    ports:
      - 80:8000
    restart: always
    volumes:
      - type: bind
        source: ./lab1
        target: /lab1/lab1
